apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minikube-pvc-1g
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: minikube-pv-1g