apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coreyapp-deploy
  name: coreyapp-deploy
spec:
  replicas: 20
  selector:
    matchLabels:
      app: coreyapp-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: coreyapp-deploy
    spec:
      containers:
      - image: mcclayac/coreyapp:v0.0.1
        name: coreyapp
        ports:
          - containerPort: 4000
        resources: {}
status: {}
