apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tonyapp-secret-deploy
  name: tonyapp-secret-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tonyapp-secret-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: tonyapp-secret-deploy
    spec:
      volumes:
        - name: database-secrets
          secret:
            secretName: database-secrets
      containers:
      - image: mcclayac/tonyapp:v0.0.19
        name: tonyapp
        volumeMounts:
          - mountPath: /opt/database-secrets
            name: database-secrets
        envFrom:
          - secretRef:
              name: database-secrets
        env:
          - name: MS_URL
            value: coreyapp-deploy-lb-svc
          - name: MS_PORT
            value: "4000"
        ports:
        - containerPort: 3000
        resources: {}
status: {}
