apiVersion: v1
kind: Service
metadata:
  labels:
    app: tonyapp-deploy
  name: tonyapp-deploy-nodeport-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tonyapp-deploy
  type: NodePort
status:
  loadBalancer: {}
