apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app2: nginx-stateful
  name: nginx-stateful
spec:
  serviceName: "nginx-stateful"
  replicas: 6
  selector:
    matchLabels:
      app2: nginx-stateful
  template:
    metadata:
      labels:
        app2: nginx-stateful
    spec:
      nodeSelector:
        minikube.k8s.io/primary: "false"
      containers:
      - image: nginx
        name: nginx-stateful
        ports:
          - containerPort: 80
