apiVersion: v1
kind: Pod
metadata:
  labels:
    run: coreyapp
  name: coreyapp
spec:
  containers:
  - image: mcclayac/coreyapp:v0.0.1
    name: coreyapp
    ports:
      - containerPort: 4000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
