apiVersion: v1
kind: Pod
metadata:
  labels:
    run: maxxapp
  name: maxxapp
spec:
  containers:
  - image: mcclayac/maxxapp:v0.0.1
    name: maxxapp
    ports:
      - containerPort: 6000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
