apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod
    app: webserver
  annotations:
    kubernetes.io/change-cause:  "Update nginx to 1.7.9"
    kubernetes.io/change-cause:  "Update back to nginx"
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
