apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tonyapp-user-pod
  name: tonyapp-user-pod
spec:
  securityContext:
    runAsUser: 1001
  containers:
  - image: mcclayac/tonyapp:v0.0.19
    name: tonyapp-user-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
