apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tonyapp
  name: tonyapp
spec:
  containers:
  - image: us-central1-docker.pkg.dev/kube-administration/tonyregistry1/tonyapp:v0.0.15
    name: tonyapp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
