apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tonyapp-sa-pod
  name: tonyapp-sa-pod
spec:
  serviceAccountName: dashboard-sa
  containers:
  - image: docker.io/mcclayac/tonyapp:v0.0.13
    name: tonyapp-sa-pod
    ports:
      - containerPort: 3000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
