apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tonyapp
  name: tonyapp
spec:
  containers:
  - image: mcclayac/tonyapp:v0.0.13
    name: tonyapp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
