apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tonyapp
  name: tonyapp
spec:
  containers:
  - image: docker.io/mcclayac/tonyapp:v0.0.13
    name: tonyapp
    command:
      - sleep
      - "5000"
    ports:
      - containerPort: 3000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
