apiVersion: apps/v1
kind: DaemonSet 
metadata:
  labels:
    run: nginx-DaemonSet
    app: webserver
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: webserver
      run: nginx-DaemonSet
  template:
    metadata:
      labels:
        app: webserver
        run: nginx-DaemonSet
    spec:
      containers:
      - image: nginx
        name: nginx-daemonset
        ports:
        - containerPort: 80
