apiVersion: v1
kind: Pod
metadata:
  labels:
    env: dev
  name: nginx-configmp-as-env-var
spec:
  containers:
  - image: nginx
    name: nginx-configmp-as-env-var
    env:
      - name: KEY1
        valueFrom:
          configMapKeyRef:
            name: custom-config
            key: customkey1
      - name: KEY2
        valueFrom:
          configMapKeyRef:
            name: custom-config
            key: customkey2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
