apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota2
  namespace: dev
spec:
  hard:
    limits.cpu: "15"
    limits.memory: 10Gi
    pods: "100"
    requests.cpu: "4"
    requests.memory: 5Gi
status: {}
