apiVersion: v1
kind: Service
metadata:
  labels:
    run: maxxapp
  name: maxxapp-pod-nodeport-svc
spec:
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    run: maxxapp
  type: NodePort
status:
  loadBalancer: {}
